apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
  namespace: udemy
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    component: redis