apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
  namespace: udemy
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    component: server